include:
- services/caddy.compose.yml
- services/cadvisor.compose.yml
- services/grafana.compose.yml
- services/node-exporter.compose.yml
- services/postgres.compose.yml
- services/prometheus.compose.yml
- services/watchtower.compose.yml
- services/xythrion.compose.yml

networks:
  infra-metrics:
    name: infra-metrics
    external: true

volumes:
  postgres_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
