include:
- deploy/caddy.compose.yml
- deploy/cadvisor.compose.yml
- deploy/grafana.compose.yml
- deploy/loki.compose.yml
- deploy/node-exporter.compose.yml
- deploy/postgres.compose.yml
- deploy/prometheus.compose.yml
- deploy/tempo.compose.yml
- deploy/watchtower.compose.yml
- deploy/xythrion.compose.yml

networks:
  database-access:
    name: database-access
    external: true
  infra-metrics:
    name: infra-metrics
    external: true

volumes:
  postgres_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
