version: "3.8"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  watchtower:
    <<: *logging

    image: "docker.io/containrrr/watchtower"

    env_file:
      - .env

    environment:
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_POLL_INTERVAL: 30

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    <<: *logging

    image: "docker.io/postgres:16-alpine"

    env_file:
      - .env

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 1s
      retries: 5

    networks:
      - database-access

networks:
  database-access:
    name: database-access
    external: true
