x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  xythrion-api:
    <<: *logging

    image: "ghcr.io/xithrius/xythrion-api:latest"

    container_name: xythrion-api

    env_file:
    - .env

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]

    ports:
    - "127.0.0.1:8001:8001"

    networks:
    - database-access
    - infra-metrics

    labels:
    - "com.centurylinklabs.watchtower.enable=true"

  xythrion-bot:
    <<: *logging

    image: "ghcr.io/xithrius/xythrion-bot:latest"

    container_name: xythrion-bot

    env_file:
    - .env

    environment:
      XYTHRION_BOT_ENVIRONMENT: "production"
      XYTHRION_BOT_INTERNAL_API_URL: "http://xythrion-api:8001"

    depends_on:
    - xythrion-api

    networks:
    - infra-metrics

    labels:
    - "com.centurylinklabs.watchtower.enable=true"
