x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  caddy:
    <<: *logging

    image: "docker.io/caddy:2.9.1"

    ports:
    - "80:80"
    - "443:443"

    volumes:
    - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config

    networks:
    - infra-metrics
