{
 "title": "API Observability",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": "xythrion-api" },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_http_requests_total{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(api_http_requests_total{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(api_http_requests_duration_seconds_sum{app_name=\"$app_name\"} / api_http_requests_duration_seconds_count{app_name=\"$app_name\"}) * 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total endpoint requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "api_http_requests_total{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "PR 50 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(endpoint, path, le) (rate(api_http_requests_duration_seconds_bucket{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"}[1m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "PR 75 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(endpoint, path, le) (rate(api_http_requests_duration_seconds_bucket{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"}[1m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "PR 90 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(endpoint, path, le) (rate(api_http_requests_duration_seconds_bucket{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"}[1m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(endpoint, path, le) (rate(api_http_requests_duration_seconds_bucket{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"}[1m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(endpoint, path, le) (rate(api_http_requests_duration_seconds_bucket{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"}[1m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "PR 99.9 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(endpoint, path, le) (rate(api_http_requests_duration_seconds_bucket{app_name=\"$app_name\", endpoint!~\"/metrics|/api/health\"}[1m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}